build_backend:
  rules:
    - if: $CI_COMMIT_BRANCH == "master"
      changes:
        - backend/**/*
      when: always

  variables:
    DOCKER_REGISTRY: docker.czumpers.com
    DOCKER_IMAGE: $DOCKER_REGISTRY/skylock

  services:
    - docker:27.3.1-dind

  stage: build_and_push
  script:
    - docker build -t $DOCKER_IMAGE:$CI_COMMIT_SHORT_SHA ./backend
    - echo "$DOCKER_REGISTRY_PASSWORD" | docker login -u "$DOCKER_REGISTRY_USER" --password-stdin $DOCKER_REGISTRY
    - docker tag $DOCKER_IMAGE:$CI_COMMIT_SHORT_SHA prod
    - docker push $DOCKER_IMAGE
