services:
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - path: .env
        required: false

    volumes:
      - ./data:/app/data
