services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"
  skylock:
    container_name: skylock
    image: docker.czumpers.com/skylock:prod
    env_file:
      - path: .env
    entrypoint: ["./entrypoint_prod.sh"]
    restart: unless-stopped
    networks:
      - traefik-public
    volumes:
      - skylock-data:/app/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.skylock.rule=Host(`skylock.czumpers.com`)"
      - "traefik.http.routers.skylock.entrypoints=websecure"
      - "traefik.http.routers.skylock.tls.certresolver=myresolver"
      - "com.centurylinklabs.watchtower.enable=true"
  dramatiq_worker:
    build:
      context: .
      dockerfile: DockerfileDramatiq
    command: >
      sh -c "PYTHONPATH=/app:$PYTHONPATH dramatiq skylock.service.dramatiq_tasks --processes 1 --threads 4 --watch ."

    depends_on:
      - redis
    env_file:
      - path: .env
        required: false
    volumes:
      - skylock-data:/app/data

networks:
  traefik-public:
    external: true

volumes:
  skylock-data:
