site_name: SkyLock CLI - Docs
site_author: Oliwier Szypczyn, Artur Kempiński, Filip Budzyński

theme:
  name: material
  palette:
    scheme: slate
    primary: blue
    accent: light blue
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.tabs
    - navigation.top
    - search.highlight
    - search.share
    - toc.integrate
    - content.code.annotate
    - content.tabs.link
    - navigation.instant
    - navigation.sections

nav:
  - Home: index.md
  - CLI Commands: cli.md
  - API:
      - Endpoints: api_endpoints.md
      - Exceptions: custom_exceptions.md

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
  - git-revision-date-localized:
      enabled: true
      type: timeago
      fallback_to_build_date: true

markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences

extra:
  social:
    - icon: fontawesome/brands/gitlab
      link: https://gitlab-stud.elka.pw.edu.pl/oszypczy/zprp-skylock
