"""Fixed shared_to column type

Revision ID: 6c2dc9a14062
Revises: 49934660337a
Create Date: 2025-05-25 13:17:40.720539

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6c2dc9a14062"
down_revision: Union[str, None] = "49934660337a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("files", schema=None) as batch_op:
        batch_op.alter_column(
            "size",
            existing_type=sa.BIGINT(),
            type_=sa.Integer(),
            existing_nullable=False,
            existing_server_default=sa.text("'0'"),
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("files", schema=None) as batch_op:
        batch_op.alter_column(
            "size",
            existing_type=sa.Integer(),
            type_=sa.BIGINT(),
            existing_nullable=False,
            existing_server_default=sa.text("'0'"),
        )

    # ### end Alembic commands ###
