"""Added email column to user with default value

Revision ID: 7b827952ecb7
Revises: a5b4e65c5e88
Create Date: 2025-04-04 15:41:17.241972

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7b827952ecb7"
down_revision: Union[str, None] = "a5b4e65c5e88"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    # 1. Dodaj kolumnę email jako nullable=True
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("email", sa.String(), nullable=True)
        )  # tymczasowo nullable=True

    # 2. Zaktualizuj istniejące rekordy, aby miały domyślną wartość
    op.execute("UPDATE users SET email = 'nullable@example.com' WHERE email IS NULL")

    # 3. Teraz zmień kolumnę na NOT NULL
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.alter_column("email", nullable=False)  # ustawiamy NOT NULL


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_column("email")

    # ### end Alembic commands ###
