"""Changed folder privacy attribute

Revision ID: 99d9495188e3
Revises: fae463122e0c
Create Date: 2025-04-18 15:44:41.954264

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99d9495188e3'
down_revision: Union[str, None] = 'fae463122e0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('folders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('privacy', sa.String(), nullable=False))
        batch_op.drop_column('is_public')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('folders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_public', sa.BOOLEAN(), nullable=False))
        batch_op.drop_column('privacy')

    # ### end Alembic commands ###
