"""Added type attibute to folder

Revision ID: cee8fbff3d11
Revises: dd6cedff4739
Create Date: 2025-04-24 19:36:45.504620

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "cee8fbff3d11"
down_revision: Union[str, None] = "dd6cedff4739"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("folders", schema=None) as batch_op:
        batch_op.add_column(sa.Column("type", sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("folders", schema=None) as batch_op:
        batch_op.drop_column("type")

    # ### end Alembic commands ###
