"""Association table shared_files changed to entity table

Revision ID: dd6cedff4739
Revises: 99d9495188e3
Create Date: 2025-04-19 13:57:40.279666

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "dd6cedff4739"
down_revision: Union[str, None] = "99d9495188e3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("shared_files", schema=None) as batch_op:
        batch_op.add_column(sa.Column("id", sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("shared_files", schema=None) as batch_op:
        batch_op.drop_column("id")

    # ### end Alembic commands ###
