"""File privacy now enum instead of literal

Revision ID: fae463122e0c
Revises: 0717d5a6c01c
Create Date: 2025-04-17 14:05:29.563687

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "fae463122e0c"
down_revision: Union[str, None] = "0717d5a6c01c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("files", schema=None) as batch_op:
        batch_op.alter_column("privacy", existing_type=sa.VARCHAR(length=9), nullable=False)
        batch_op.create_check_constraint(
            "ck_files_privacy_valid",
            'privacy IN ("private", "protected", "public")',
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("files", schema=None) as batch_op:
        batch_op.drop_constraint(
            "ck_files_privacy_valid",
            type_="check",
        )
        batch_op.alter_column("privacy", existing_type=sa.VARCHAR(length=9), nullable=True)

    # ### end Alembic commands ###
